{"level":"error","message":"Sign up error signUpSchema is not defined","service":"acquisitions-api","stack":"ReferenceError: signUpSchema is not defined\n    at signup (file:///home/sowmik/code/acquisitions/src/controllers/auth.controller.js:5:30)\n    at Layer.handleRequest (/home/sowmik/code/acquisitions/node_modules/router/lib/layer.js:152:17)\n    at next (/home/sowmik/code/acquisitions/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/home/sowmik/code/acquisitions/node_modules/router/lib/route.js:117:3)\n    at handle (/home/sowmik/code/acquisitions/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/home/sowmik/code/acquisitions/node_modules/router/lib/layer.js:152:17)\n    at /home/sowmik/code/acquisitions/node_modules/router/index.js:295:15\n    at processParams (/home/sowmik/code/acquisitions/node_modules/router/index.js:582:12)\n    at next (/home/sowmik/code/acquisitions/node_modules/router/index.js:291:5)\n    at Function.handle (/home/sowmik/code/acquisitions/node_modules/router/index.js:186:3)"}
{"level":"error","message":"Sign up error formatValidationErrors is not defined","service":"acquisitions-api","stack":"ReferenceError: formatValidationErrors is not defined\n    at signup (file:///home/sowmik/code/acquisitions/src/controllers/auth.controller.js:10:18)\n    at Layer.handleRequest (/home/sowmik/code/acquisitions/node_modules/router/lib/layer.js:152:17)\n    at next (/home/sowmik/code/acquisitions/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/home/sowmik/code/acquisitions/node_modules/router/lib/route.js:117:3)\n    at handle (/home/sowmik/code/acquisitions/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/home/sowmik/code/acquisitions/node_modules/router/lib/layer.js:152:17)\n    at /home/sowmik/code/acquisitions/node_modules/router/index.js:295:15\n    at processParams (/home/sowmik/code/acquisitions/node_modules/router/index.js:582:12)\n    at next (/home/sowmik/code/acquisitions/node_modules/router/index.js:291:5)\n    at Function.handle (/home/sowmik/code/acquisitions/node_modules/router/index.js:186:3)"}
{"level":"error","message":"Sign up error password is not defined","service":"acquisitions-api","stack":"ReferenceError: password is not defined\n    at signup (file:///home/sowmik/code/acquisitions/src/controllers/auth.controller.js:20:50)\n    at Layer.handleRequest (/home/sowmik/code/acquisitions/node_modules/router/lib/layer.js:152:17)\n    at next (/home/sowmik/code/acquisitions/node_modules/router/lib/route.js:157:13)\n    at Route.dispatch (/home/sowmik/code/acquisitions/node_modules/router/lib/route.js:117:3)\n    at handle (/home/sowmik/code/acquisitions/node_modules/router/index.js:435:11)\n    at Layer.handleRequest (/home/sowmik/code/acquisitions/node_modules/router/lib/layer.js:152:17)\n    at /home/sowmik/code/acquisitions/node_modules/router/index.js:295:15\n    at processParams (/home/sowmik/code/acquisitions/node_modules/router/index.js:582:12)\n    at next (/home/sowmik/code/acquisitions/node_modules/router/index.js:291:5)\n    at Function.handle (/home/sowmik/code/acquisitions/node_modules/router/index.js:186:3)"}
{"level":"error","message":"Error creating user: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: Test User,test@example.com,$2b$10$rCbN9iObQuJn9q8je/k27uyFUzrG.tCL2R8ETCwDywfhUkbuFYtlG,user","service":"acquisitions-api"}
{"level":"error","message":"Sign up error Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: Test User,test@example.com,$2b$10$rCbN9iObQuJn9q8je/k27uyFUzrG.tCL2R8ETCwDywfhUkbuFYtlG,user","service":"acquisitions-api","stack":"Error: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: Test User,test@example.com,$2b$10$rCbN9iObQuJn9q8je/k27uyFUzrG.tCL2R8ETCwDywfhUkbuFYtlG,user\n    at createUser (file:///app/src/services/auth.service.js:50:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signup (file:///app/src/controllers/auth.controller.js:20:18)"}
{"level":"error","message":"Error creating user: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$9hc7jKcIWu.199tNE.VHnuddvm.PD.rkVuNSKljvdblRPIiIK7Hdm,user","service":"acquisitions-api"}
{"level":"error","message":"Sign up error Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$9hc7jKcIWu.199tNE.VHnuddvm.PD.rkVuNSKljvdblRPIiIK7Hdm,user","service":"acquisitions-api","stack":"Error: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$9hc7jKcIWu.199tNE.VHnuddvm.PD.rkVuNSKljvdblRPIiIK7Hdm,user\n    at createUser (file:///app/src/services/auth.service.js:50:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signup (file:///app/src/controllers/auth.controller.js:20:18)"}
{"level":"error","message":"Error creating user: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$ZCYi/FvMnL3jOtYzbif6xu3ixlK4TlCMFf6OCAiFu8te5wF263LAC,user","service":"acquisitions-api"}
{"level":"error","message":"Sign up error Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$ZCYi/FvMnL3jOtYzbif6xu3ixlK4TlCMFf6OCAiFu8te5wF263LAC,user","service":"acquisitions-api","stack":"Error: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$ZCYi/FvMnL3jOtYzbif6xu3ixlK4TlCMFf6OCAiFu8te5wF263LAC,user\n    at createUser (file:///app/src/services/auth.service.js:50:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signup (file:///app/src/controllers/auth.controller.js:20:18)"}
{"level":"error","message":"Error creating user: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$2UCS.loR7CWCGo0iuG7pzuI4/C9Q/cTgblHA.FlO5ytj7dH2pYXx6,user","service":"acquisitions-api"}
{"level":"error","message":"Sign up error Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$2UCS.loR7CWCGo0iuG7pzuI4/C9Q/cTgblHA.FlO5ytj7dH2pYXx6,user","service":"acquisitions-api","stack":"Error: Error: Failed query: insert into \"users\" (\"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\") values (default, $1, $2, $3, $4, default, default) returning \"id\", \"name\", \"email\", \"role\", \"created_at\"\nparams: test,test2@xxx.com,$2b$10$2UCS.loR7CWCGo0iuG7pzuI4/C9Q/cTgblHA.FlO5ytj7dH2pYXx6,user\n    at createUser (file:///app/src/services/auth.service.js:50:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signup (file:///app/src/controllers/auth.controller.js:20:18)"}
{"level":"error","message":"Error getting users Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?","service":"acquisitions-api","stack":"Error: Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?\n    at PgDialect.buildSelectQuery (file:///app/node_modules/drizzle-orm/pg-core/dialect.js:251:15)\n    at PgSelectBase.getSQL (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:728:25)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:771:66\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase._prepare (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:769:19)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:797:19\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase.execute (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:796:19)\n    at PgSelectBase.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","service":"acquisitions-api"}
{"level":"error","message":"Error getting users Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?","service":"acquisitions-api","stack":"Error: Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?\n    at PgDialect.buildSelectQuery (file:///app/node_modules/drizzle-orm/pg-core/dialect.js:251:15)\n    at PgSelectBase.getSQL (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:728:25)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:771:66\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase._prepare (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:769:19)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:797:19\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase.execute (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:796:19)\n    at PgSelectBase.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","service":"acquisitions-api"}
{"level":"error","message":"Error getting users Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?","service":"acquisitions-api","stack":"Error: Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?\n    at PgDialect.buildSelectQuery (file:///app/node_modules/drizzle-orm/pg-core/dialect.js:251:15)\n    at PgSelectBase.getSQL (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:728:25)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:771:66\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase._prepare (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:769:19)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:797:19\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase.execute (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:796:19)\n    at PgSelectBase.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","service":"acquisitions-api"}
{"level":"error","message":"Error getting users Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?","service":"acquisitions-api","stack":"Error: Your \"id\" field references a column \"users\".\"id\", but the table \"users\" is not part of the query! Did you forget to join it?\n    at PgDialect.buildSelectQuery (file:///app/node_modules/drizzle-orm/pg-core/dialect.js:251:15)\n    at PgSelectBase.getSQL (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:728:25)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:771:66\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase._prepare (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:769:19)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:797:19\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase.execute (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:796:19)\n    at PgSelectBase.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","service":"acquisitions-api"}
{"level":"error","message":"Error getting users Your \"id\" field references a column \"user\".\"id\", but the table \"user\" is not part of the query! Did you forget to join it?","service":"acquisitions-api","stack":"Error: Your \"id\" field references a column \"user\".\"id\", but the table \"user\" is not part of the query! Did you forget to join it?\n    at PgDialect.buildSelectQuery (file:///app/node_modules/drizzle-orm/pg-core/dialect.js:251:15)\n    at PgSelectBase.getSQL (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:728:25)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:771:66\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase._prepare (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:769:19)\n    at file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:797:19\n    at Object.startActiveSpan (file:///app/node_modules/drizzle-orm/tracing.js:8:14)\n    at PgSelectBase.execute (file:///app/node_modules/drizzle-orm/pg-core/query-builders/select.js:796:19)\n    at PgSelectBase.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","service":"acquisitions-api"}
{"cause":{"name":"NeonDbError","sourceError":{}},"level":"error","message":"Error getting users Failed query: select \"id\", \"email\", \"name\", \"role\", \"created_at\", \"updated_at\" from \"users\"\nparams: ","params":[],"query":"select \"id\", \"email\", \"name\", \"role\", \"created_at\", \"updated_at\" from \"users\"","service":"acquisitions-api","stack":"Error: Failed query: select \"id\", \"email\", \"name\", \"role\", \"created_at\", \"updated_at\" from \"users\"\nparams: \n    at NeonHttpPreparedQuery.queryWithCache (file:///home/sowmik/code/acquisitions/node_modules/drizzle-orm/pg-core/session.js:41:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async NeonHttpPreparedQuery.execute (file:///home/sowmik/code/acquisitions/node_modules/drizzle-orm/neon-http/session.js:45:20)\n    at async getAllUsers (file:///home/sowmik/code/acquisitions/src/services/users.service.js:8:12)\n    at async file:///home/sowmik/code/acquisitions/[eval1]:8:17"}
{"level":"error","message":"Error authenticating user: Error: User with this email does not exist","service":"acquisitions-api"}
{"level":"error","message":"Sign in error User with this email does not exist","service":"acquisitions-api","stack":"Error: User with this email does not exist\n    at authenticateUser (file:///app/src/services/auth.service.js:84:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signin (file:///app/src/controllers/auth.controller.js:61:18)"}
{"level":"error","message":"Error authenticating user: Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: test3@xxx.com,1","service":"acquisitions-api"}
{"level":"error","message":"Sign in error Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: test3@xxx.com,1","service":"acquisitions-api","stack":"Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: test3@xxx.com,1\n    at authenticateUser (file:///app/src/services/auth.service.js:84:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signin (file:///app/src/controllers/auth.controller.js:61:18)"}
{"level":"error","message":"Error authenticating user: Error: Invalid password","service":"acquisitions-api"}
{"level":"error","message":"Sign in error Invalid password","service":"acquisitions-api","stack":"Error: Invalid password\n    at authenticateUser (file:///app/src/services/auth.service.js:84:11)\n    at async signin (file:///app/src/controllers/auth.controller.js:61:18)"}
{"level":"error","message":"Error creating user: Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: admin@xxx.com,1","service":"acquisitions-api"}
{"level":"error","message":"Sign up error Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: admin@xxx.com,1","service":"acquisitions-api","stack":"Error: Error: Failed query: select \"id\", \"name\", \"email\", \"password\", \"role\", \"created_at\", \"updated_at\" from \"users\" where \"users\".\"email\" = $1 limit $2\nparams: admin@xxx.com,1\n    at createUser (file:///app/src/services/auth.service.js:50:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async signup (file:///app/src/controllers/auth.controller.js:20:18)"}
